 
- name: print
  debug:
    msg: "{{ ansible_facts.default_ipv4.address }}"
  become: yes

- name: Add deadsnakes PPA
  apt_repository:
    repo: ppa:deadsnakes/ppa
    state: present
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes

- name: Install Python3.9
  apt:
    name: python3.9
    state: present
  become: yes

- name: Install packages
  become: yes
  apt:
    name:
      - apache2
      - apache2-dev
      - python3-pip
      - libmysqlclient-dev
      - libjpeg-dev
      - python3.9-dev
      - python3.9-distutils
    state: present

- name: remove django_project
  command: rm -rf /django_project
  become: yes

- name: git clon
  git:
    repo: https://github.com/gugucone999/django-project.git
    dest: /django_project
    update: yes
  become: yes

- name: Install virtualenv
  pip:
    name: virtualenv
    executable: pip3
  become: yes

- name: Remove venv
  command: rm -rf /django_project/venv
  become: yes

- name: Create a virtual environment
  become: yes
  command: virtualenv venv
  args:
    chdir: /django_project

- name: Activate virtual environment
  shell: source /django_project/venv/bin/activate
  args:
    executable: /bin/bash

- name: Install requirements
  pip:
    requirements: /django_project/requirements.txt
    virtualenv: /django_project/venv
    state: present
  become: yes

- name: Install mod_wsgi
  pip:
    name: mod_wsgi
    virtualenv: /django_project/venv
    state: present
  become: yes

- name: Copy Files settings
  template:
    src: settings.py.j2
    dest: /django_project/config/settings.py
    remote_src: no
  become: yes

- name: Copy Files 000-default.conf
  template:
    src: 000-default.conf.j2
    dest: /etc/apache2/sites-enabled/000-default.conf
    remote_src: no
  become: yes

- name: migrate
  shell: |
    source /django_project/venv/bin/activate
    python3 /django_project/manage.py migrate & wait
  args:
    executable: /bin/bash
  become: yes

- name: Restart Apache
  systemd:
    name: apache2
    state: restarted
  become: yes






