name: Deploy with Terraform and Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          wget https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip
          unzip terraform_1.0.5_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Deploy infrastructure
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@<13.209.4.108> 'cd ~/terraform; terraform init; terraform apply --auto-approve'

      - name: Configure Ansible inventory
        run: |
          echo "[webserver]" > inventory
          echo "<13.209.4.108>" >> inventory

      - name: Deploy application with Ansible
        run: |
          ansible-playbook -i inventory playbook.yml --private-key ~/.ssh/id_rsa --user ubuntu