name: 'Deploy'

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Check for changes
      run: |
        git fetch
        if git diff --quiet HEAD $(git rev-parse origin/master); then
          echo "::set-output name=changes::no"
        else
          echo "::set-output name=changes::yes"
        fi
      id: changes


    - name: SSH Commands
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.AWS_SSH_HOST }}
        username: ${{ secrets.AWS_SSH_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        port: ${{ secrets.AWS_SSH_PORT }}
        script_stop: true
        script: |
          sudo rm -rf /tmp
          sudo rm -rf /project
          sudo mkdir /project
          sudo git clone https://github.com/gugucone999/mini.git /tmp
          sudo cp -r /tmp/* /project
          sudo ls -al
          sudo sh /project/run.sh


          