name: 'Deploy'

on:
  push:
    branches: [ "master" ]
  pull_request:

permissions:
  contents: read

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: SSH Commands
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.AWS_SSH_HOST }}
        username: ${{ secrets.AWS_SSH_USERNAME }}
        key: ${{ secrets.AWS_SSH_KEY }}
        port: ${{ secrets.AWS_SSH_PORT }}
        script_stop: true
        script: |
          sudo rm -rf /project
          sudo git clone https://github.com/gugucone999/mini.git /project
          sudo terraform -chdir=/project/terraform apply -auto-approve
          sudo aws elasticache describe-cache-clusters \
            --cache-cluster-id ec-project \
            --show-cache-node-info > /home/ubuntu/elasticache.json